### ISSUE TITLE
About using your own pictures for reasoning tests

### ISSUE THREAD

**Issue by Zlin0530** [Yueming6568/DeltaEdit#4]
This is an amazing job！ I want to test inference with my own dataset, how should I do it?

**Comment by Yueming6568** [comment]
Thanks for your interest. If you want to test with real images, you can extract w+ space features of real images with [e4e](https://github.com/omertov/encoder4editing) model and map to get S-space features and extract image embeddings of real images with CLIP model. Using these features, you can implement the corresponding edits. We will also release the code related to real images around June (since I'm busy this time), and you are welcome to wait.

**Comment by Zlin0530** [comment]
> 感谢您的关注。如果要用真实图像进行测试，可以用[e4e](https://github.com/omertov/encoder4editing)模型提取真实图像的w+空间特征，映射得到S空间特征，用CLIP模型提取真实图像的image embeddings。使用这些功能，您可以实现相应的编辑。我们也会在6月左右（因为这段时间比较忙）放出实图相关的代码，欢迎大家期待。

Thanks for the quick reply, I've tested it successfully, thanks again for your great work!

**Comment by 123456klk1** [comment]
> > 谢谢您的注意。如果要用真人图像进入测试，可以用[e4e](https://github.com/omertov/encoder4editing)模型提取真人图像的w+空间特征，映射到S空间特征，用CLIP模型提取真实图像的图像填入。使用这些功能，您可以实际应用的编辑。我们也会在6月左右（因为这段时间比较忙）放出实物图相关的代号，欢迎大家期待。
> 
> 感谢您的快速回复，我已经测试成功，再次感谢您的出色工作！

您好，这个部分您是怎么完成的？

**Comment by Yueming6568** [comment]
Hi  @123456klk1, I will release this code in this week! Please wait for me~ Thank you~

**Comment by 123456klk1** [comment]
Thank you so much, I'm looking forward to it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月7日(星期三) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Yueming6568/DeltaEdit] About using your own pictures for reasoning tests (Issue #4)





 
Hi  @123456klk1, I will release this code in this week! Please wait for me~ Thank you~

**Comment by Yueming6568** [comment]
Hi @123456klk1 , the test code for real images is released : )

**Comment by pyh007** [comment]
你好 如果想要将张嘴的人物变为闭嘴如何训练
